### PR TITLE
Up build number to rebuild feedstock

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
In the last build, the build for python 3.7 failed for some weird reason (see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=240019&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05). This PR bumps the build number to get a fresh build for python 3.7.

This is needed for https://github.com/conda-forge/staged-recipes/pull/14250

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @nfahlgren.

/cc @wolfv

**Comment by nfahlgren** [comment]
Thanks @Tobias-Fischer!

**Pull request merged**
